A4 s 152
BuzzTech-API/Synergy-FrontEnd pull request #55
Opened 2024-05-30 19:05 UTC by PedrohDavi

Feita a correção nos modais de editar sala, ambos estão funcionais e editando corretamente.
Obrigado aos que se disponibilizaram pra ajuda!
Qualquer desconformidade me comuniquem.

2024-05-30 19:10 UTC, lima2206 commented on app/constants.ts
na hora de commitar se puder não commitar essa parte é bom. só desselecionar na hora do add

2024-05-30 19:13 UTC, lima2206 requested changes
Se o resto foi testado então além do outro comentário ta tudo certo

2024-05-30 19:13 UTC, lima2206 commented on app/constants.ts
na hora de commitar se puder não commitar essa parte é bom. só desselecionar na hora do add

2024-05-30 19:13 UTC, lima2206 commented on app/constants.ts
se não fica dando conflito, depois da até pra ver se adiciona no git ignore

2024-06-05 18:39 UTC, Ivan-Duarte approved these changes

2024-06-05 19:33 UTC, lima2206 approved these changes

2024-06-05 19:33 UTC, merged